chore: update repo semaphore config

diff --git a/.semaphore/semaphore.yml b/.semaphore/semaphore.yml
--- a/.semaphore/semaphore.yml
+++ b/.semaphore/semaphore.yml
@@ -34,7 +34,7 @@ blocks:
     dependencies: []
     run:
       # don't run the tests on non-functional changes...
-      when: "change_in('/', {exclude: ['/.deployed-versions/', '.github/', 'service.yml', 'README.md'], default_branch: 'master'})"
+      when: "change_in('/', {exclude: ['/.deployed-versions/', '/.github/', '/service.yml', '/README.md'], default_branch: 'master'})"
     task:
       jobs:
         - name: Test
@@ -77,29 +77,17 @@ blocks:
           commands:
             - git clone --branch master --single-branch git@github.com:confluentinc/connect-releases.git
             - ./connect-releases/tasks/release-connect-plugins/generate-connect-changelogs.sh
-
-  - name: Connector Kafka Docker Playground Test
+  # Claude Code based code review in PRs.
+  - name: R2 Code Review
     dependencies: []
     run:
-      # Run this block only for pull requests
-      when: "pull_request =~ '.*'"
+      when: "pull_request =~ '.+' and change_in('/', {exclude: ['/.deployed-versions/']})"
     task:
       jobs:
-        - name: Trigger Kafka Docker Playground Test
+        - name: R2 Code Review
           commands:
-            # Don't run this block if target branch for PR is not a nightly branch or master branch
-            - |
-              if [[ "$SEMAPHORE_GIT_BRANCH" =~ ^[0-9]+\.[0-9]+\.x$ ]] || [[ "$SEMAPHORE_GIT_BRANCH" == "master" ]] ; then \
-                echo "PR is targeted to ${SEMAPHORE_GIT_BRANCH} branch which is feature or master branch. Triggering run-kdp-matrix-on-pr-builds task."; \
-                sem-trigger -p connect-ci-cd-pipelines \
-                  -t run-kdp-matrix-on-pr-builds \
-                  -b master \
-                  -i "REPO_NAME:$(basename $SEMAPHORE_GIT_REPO_SLUG)" \
-                  -i "BRANCH_NAME:${SEMAPHORE_GIT_PR_BRANCH}" \
-                  -w
-              else \
-                echo "PR is targeted to ${SEMAPHORE_GIT_BRANCH} branch which is not feature or master branch. Skipping Kafka Docker Playground Test Task."; \
-              fi;
+            # || true: code review failures are unrelated to the codebase and should not block CI. Please report issues to Slack channel #r2.
+            - r2 code-review --verbose --timeout=900s || true
 
 after_pipeline:
   task:
